<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <ItemGroup>
    <!-- Runtime -->
    <PackageVersion Include="Serilog" Version="3.1.1" />
    <!-- Injected into every project via Directory.Build.targets -->
    <PackageVersion Include="Microsoft.SourceLink.GitHub" Version="8.0.0" />
    <!-- Stale -->
    <PackageVersion Include="MediatR" Version="12.4.0" />
  </ItemGroup>
</Project>
